name: Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  GO_VERSION: "1.24"
  GOLANGCI_LINT_VERSION: v1.64.8

jobs:
  run-lint-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: CI=CI GOWORK=off go test -v ./...